input_dir: 'input/data/'
input_dir_mappings: 'input/data/'
output_dir: 'output/'
input_fn: 'Input_file.xlsx'
lr_rate: 0.05
models:
  LinearMDP:
    n_sim: 20
    beta: 5
    nr_gd_steps: 100
    d: 2
    N: 2 #{0,1,...,N} hence N+1 length markov chain. So, we have three rows of w. 
    true_theta: #(N+1) x d matrix
      #- [1-2e-10, 1e-10, 1e-10]
      #- [1e-10, 1-2e-10, 1e-10]
      #- [1e-10, 1e-10, 1-2e-10]
      - [0.1, 0.9]
      - [0.7, 0.3]
      - [0.5, 0.5]
    init_theta: #(N+1) x d matrix
      #- ['0.5', '0.25', '0.25']
      #- [0.5, 0.25, 0.25]
      #- [0.5, 0.25, 0.25]
      #- [0.5, 0.25, 0.25]
      #- [0.5, 0.25, 0.25]
      - [0.5, 0.5]
      - [0.5, 0.5]
      - [0.5, 0.5]

