input_dir: 'input/data/'
input_dir_mappings: 'input/data/'
output_dir: 'output'
input_fn: 'Input_file.xlsx'
models:
  LinearMDP:
    n_sim: 100
    bound: -2,2
    beta: 0.1
    d: 2
    N: 2 #{0,1,...,N} hence N+1 length markov chain. So, we have three rows of w. 
    true_w:
      - [0, 0]
      - [0, 0]
      - [0, 0]
    nr_sg_steps: 100
    init_w:
      - [0.5, 0.2]
      - [0.5, 0.2]
      - [0.5, 0.2]

