input_dir: 'src/generation/data/'
input_dir_mappings: 'src/generation/data/'
output_dir: 'src/generation/output/'
input_fn: 'Input_file.xlsx'
general:
  d: 3
  n_samples: 2000
  dt: 0.001
  T: 1
  beta_min: 0.001
  beta_max: 3
pde_solver:
  C:
    - [1, 0, 0]
    - [0, 0, 1]
  t_low: 1e-10
  x_low: -1.5
  nSim_interior: 2000
  nSim_terminal: 2000
  x_high: 1.5
  x_multiplier: 1.5
  sampling_stages: 100 #100
  steps_per_sample: 10
  learning_rate: 0.001
pre_trained:
  data:
    batch_size: 50
    dt: 0.001
  model:
    nodes_per_layer: 50
    num_layers: 3
    learning_rate: 0.001
    N_epochs: 3_000 #3_000
    batch_size: 20









